# ==================================================================
# sacred-yaml-torch-tf-py36
# ------------------------------------------------------------------
# anconda3      5.2.0  (curl)
# python        3.6    (apt)
# pytorch       0.4.1  (pip)
# tensorflow    1.4.0  (pip)
# sacred        0.7.5  (pip)
# yaml          5.1    (pip)
# ==================================================================

FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

# Install some dependencies
RUN apt-get update && apt-get install -y \
	bc \
	build-essential \
	cmake \
	curl \
	g++ \
	net-tools \
	inetutils-ping \
	nginx \
	wget \
	curl \
	gfortran \
	git \
	libffi-dev \
	libfreetype6-dev \
	libhdf5-dev \
	libjpeg-dev \
	liblcms2-dev \
	libopenblas-dev \
	liblapack-dev \
	libpng12-dev \
	libssl-dev \
	libtiff5-dev \
	libwebp-dev \
	libzmq3-dev \
	nano \
	pkg-config \
	software-properties-common \
	unzip \
	vim \
	wget \
	zlib1g-dev \
	qt5-default \
	libvtk6-dev \
	zlib1g-dev \
	libjpeg-dev \
	libwebp-dev \
	libpng-dev \
	libtiff5-dev \
	libjasper-dev \
	libopenexr-dev \
	libgdal-dev \
	libdc1394-22-dev \
	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libtheora-dev \
	libvorbis-dev \
	libxvidcore-dev \
	libx264-dev \
	yasm \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	libv4l-dev \
	libxine2-dev \
	libtbb-dev \
	libeigen3-dev \
	openssh-server \
	ant \
	tmux \
	default-jdk \
	doxygen \
	&& \
    apt-get clean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* && \
    # Link BLAS library to use OpenBLAS using the alternatives mechanism (https://www.scipy.org/scipylib/building/linux.html#debian-ubuntu)
    update-alternatives --set libblas.so.3 /usr/lib/openblas-base/libblas.so.3
# Install Anaconda3
RUN curl -o /tmp/anaconda.sh https://mirrors.tuna.tsinghua.edu.cn/anaconda/archive/Anaconda3-5.2.0-Linux-x86_64.sh && \
    chmod +x /tmp/anaconda.sh && \
    bash /tmp/anaconda.sh -b -p ~/anaconda3 && \ 
    rm /tmp/anaconda.sh && \
    echo 'export PATH="/root/anaconda3/bin:$PATH"' >> ~/.bashrc && \
    . ~/.bashrc  && \
    conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free && \
    conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main && \
    conda config --set show_channel_urls yes && \
	
    # pip install tensorflow-gpu:lastest, torch and others
    pip install tensorflow-gpu==1.4.0 \
	torch==0.4.1 \
	torchvision==0.2.0 \
 	imageio==2.3.0 \
	scipy==1.1.0 \
	argparse==1.4.0 \
	Pillow==5.1.0 \
	sacred==0.7.5 \
	pymongo==3.9.0 \
	pyyaml==5.1 \
	visdom \
	shapely \
	msgpack \
	h5py==2.8.0 \
	pypng \ 
	sklearn \
	easydict==1.9 \
	image \
    opencv-python==3.4.4.19 \
	&& \
    # Install opencv-python 3.4		
    conda clean --all && \
    rm -r ~/.cache/pip/* 

